//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_5_Upload.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product_Image
    {
        public int C_id { get; set; }
        public int C_id_pro { get; set; }
        public string C_file_name { get; set; }
        public int C_priority { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_Product Tbl_Product1 { get; set; }
    }
}
